alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - alertmanager.astralinux.slebedev.ru
    pathType: Prefix

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - grafana.astralinux.slebedev.ru
    pathType: Prefix

prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - prometheus.astralinux.slebedev.ru
    pathType: Prefix