---
- name: Установка KubeVirt
  ansible.biltin.command: "kubectl apply -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-{{ kubevirt_version }}.yaml"

- name: Запуск виртуальной машины
  kubernetes.core.k8s:
    state: present
    src: templates/kubevirt-vm.yml.j2
