#!groovy
// Run docker build
pipeline {
    agent {
        label 'built-in'
        }
    triggers { pollSCM('* * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    environment {
    BUILD_TAG_NAME = '$BUILD_NUMBER'
    IMAGE_BASE = "l1is/wonder_app"
    DOCKER_REPO_NAME = 'l1is'
    IMAGE_NAME = "wonder_app"
    CHART_NAME = 'wonder-app-chart'
    }
    stages {
        stage("Docker Login") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker login -u $USERNAME --password $PASSWORD
                    """
                }
            }
        }
        stage("Create Docker Image") {
            when { triggeredBy 'SCMTrigger' }
            steps {
                dir ('.') {
                	sh """
                    docker build -t $IMAGE_BASE:$BUILD_TAG_NAME .
                    """
                }
            }
        }
        stage("Create Docker Image with Tag") {
            when { buildingTag() }
            steps {
                dir ('.') {
                	sh """
                    docker build -t $IMAGE_BASE:$TAG_NAME .
                    """
                }
            }
        }
        stage("Docker Push") {
            when { triggeredBy 'SCMTrigger' }
            steps {
                sh """
                docker push $IMAGE_BASE:$BUILD_TAG_NAME
                """
            }
        }
        stage("Create Push with Tag") {
            when { buildingTag() }
            steps {
                dir ('.') {
                	sh """
                    docker push $IMAGE_BASE:$TAG_NAME
                    """
                }
            }
        }
        stage("Deploy App") {
            when { buildingTag() }
            steps {
                sh """
                helm upgrade app-prod wonder-app-chart --set image_frontend.tag=$TAG_NAME --install
                """
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}